### ISSUE TITLE
Missing `build.inc` for `build.sp`

### ISSUE THREAD

**Issue by ShadowMen** [Phil25/FrolicsomePluginsOfImpracticality#1]
The include of `build` in `build.sp` throws error, because in this repository there is no `build.inc`. So I can't build the plugin. I've searched the web and alliedmodders for that file, but I can't find it.

Maybe you have it laying around in your storage. If so, then could you please provide it?

Cool plugin by the way :wink:

**Comment by Phil25** [comment]
Yeah here you go!
[build.txt](https://github.com/Phil25/FrolicsomePluginsOfImpracticality/files/4022905/build.txt)

Change the file type from `.txt` to `.inc`, GitHub doesn't allow me to upload it as `.inc`.

It's just a collection of enums that I separated for some reason. Hopefully this will compile with new decls, I haven't been in plugin development for quite a while.
